/*
@TargetNode='localhost'
@GeneratedBy=SimpleDscConfiguration
@GenerationDate=01/12/2026 14:43:00
@GenerationHost=localhost
*/
instance of MSFT_ServiceResource as $MSFT_ServiceResource1ref
{
ResourceID = "[Service]SampleService";
 Name = "SampleService";
 State = "Running";
 SourceInfo = "::5::3::Service";
 ModuleName = "PSDscResources";
 ModuleVersion = "2.12.0.0";
 ConfigName = "SimpleDscConfiguration";
};
